RADAR-base/RADAR-Docker

dcompose-stack/radar-cp-hadoop-stack/README.md
dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
dcompose-stack/radar-cp-hadoop-stack/extract_from_hdfs.sh
dcompose-stack/radar-cp-stack/docker-compose.yml

Added a hadoop container, including functionality to extract data, in the `dcompose-stack/radar-cp-hadoop-stack/` directory.
I also found out how to run the Confluent docker containers without using `--net=host`, see `dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml`. This means the setup also runs on Mac and that it does not open any unneeded ports on the host.

Hadoop container

---

dcompose-stack/radar-cp-hadoop-stack/README.md
dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
dcompose-stack/radar-cp-hadoop-stack/hdfs-namenode/Dockerfile
dcompose-stack/radar-cp-hadoop-stack/hdfs-namenode/run.sh

This way, the name node stores the directory information (+- like filesystem inodes) in duplicate. By mounting the name directory on different volumes, some redundancy in data can be achieved.
The run script is based on the run script of [uhopper/hadoop-namenode](https://bitbucket.org/uhopper/hadoop-docker/src/bf2f18501802/namenode/?at=master), except that it supports multiple name node directories.

Support for multiple name node directories.

---

dcompose-stack/radar-security-only-stack/.env
dcompose-stack/radar-security-only-stack/docker-compose.yml
dcompose-stack/radar-security-only-stack/wso2is/carbon.xml
dcompose-stack/radar-security-only-stack/wso2is/master-datasources.xml
dcompose-stack/radar-security-only-stack/wso2is/registry.xml
dcompose-stack/radar-security-only-stack/wso2is/user-mgt.xml

Changed to WSO2IS version 5.3.0 (was 5.0.0)
Removed use of mysql database (now should use embedded LDAP)
Removed references to unused WSO2 packages

Use WSO2 v5.3.0 and remove mysql

---

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
dcompose-stack/radar-cp-hadoop-stack/kafka-radarinit/topic_init.sh
images/radar-hdfs-connector/kafka_status.sh
images/radar-mongodb-connector/kafka_status.sh

Connectors no longer rely on `Rest-Proxy` for checking topics availability. The check is now done using `kaka-topics`.
Note: the same check should be done on the RADAR-Backend container too. This change requires to build the Backend container from a different docker image.

Kafka-shell for checking topics availability

---

dcompose-stack/radar-cp-hadoop-stack/etc/managementportal/changelogs/config/liquibase/oauth_client_details.csv.template

These scopes can not be empty, it prevents a token from being created. We can simply add a dummy scope since these apps will inherit the permissions from the user that logs in.

Add dummy scope for OAuth clients that use a user login

---

dcompose-stack/radar-cp-hadoop-stack/etc/managementportal/config/liquibase/oauth_client_details.csv.template

Change scope of `ManagementPortalapp` client because it does not work with `DUMMY_SCOPE`. Currently it requires a scope of `read,write` to work.

Change ManagementPortalapp client scope

---

dcompose-stack/radar-cp-hadoop-stack/docker-prune.sh
dcompose-stack/radar-cp-hadoop-stack/kafka-radarinit/init.sh

fixing a bug introduced in https://github.com/RADAR-CNS/RADAR-Docker/pull/80
Edit: also fixes `docker-prune.sh` to use bash, to work with `util.sh`

bugfix: print to stderr

---

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
dcompose-stack/radar-cp-hadoop-stack/etc/radar.yml.template

Small fixes:
- fixed persistence path for monitors (enables data persistence between restarts for monitors)
- reduced unnecessary Kafka logging
- increased Kafka health check timeout
- allow backend to query the Google play store
- fixed gateway health check

Docker compose fixes

---

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
dcompose-stack/radar-cp-hadoop-stack/kafka-radarinit/Dockerfile
images/radar-backend-kafka/Dockerfile

Use the latest version of RADAR-Schemas in kafka-init so that all the new schemas are also registered
Also use latest version of RADAR-Backend with Phone streams

Use latest RADAR-Schema version

---

dcompose-stack/radar-cp-hadoop-stack/etc/webserver/cors.conf

Should fix RADAR-base/ManagementPortal#258, by hiding any `Access-Control-Allow-Origin` sent by the proxied service if CORS is enabled in Nginx.

Fixed duplicate cors header

---

dcompose-stack/radar-cp-hadoop-stack/bin/docker-prune
dcompose-stack/radar-cp-hadoop-stack/bin/radar-docker

- Also remove third HDFS data node on prune
- Do not recreate dependent services after `radar-docker rebuild SERVICE...`

Tweak command scripts

---

dcompose-stack/radar-cp-hadoop-stack/bin/hdfs-restructure

Issues fixed:
- Corrupted zip files were not updated anymore. Recreating when this occurs
- Optimisation to only process files that were updated more recently than the snapshot

Only snapshot updated files and check zip integrity

---

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml

The variables for kafka-init in docker-compose were not the ones used in the Dockerfile. Changed them to their actual values.
This will not affect existing topics though. To change the replication factor of existing topics, based on a comment from Stackoverflow, the following should work:
```bash
docker-compose exec kafka-1 /bin/bash
function expandTopicsFrom2To3() {
TOPIC=$1
echo '{"version":1,"partitions":[{"topic":"'${TOPIC}'","partition":0,"replicas":[1,2,3]},{"topic":"'${TOPIC}'","partition":2,"replicas":[1,2,3]},{"topic":"'${TOPIC}'","partition":1,"replicas":[1,2,3]}]}' > /tmp/topics-to-expand.json
kafka-reassign-partitions --zookeeper zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181 --execute --reassignment-json-file /tmp/topics-to-expand.json
kafka-topics --zookeeper …
```

Fix replication factor

---

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
dcompose-stack/radar-cp-hadoop-stack/lib/systemd/radar-renew-certificate.timer.template

Portainer version 1.19.1 is not available on docker hub anymore. So update to the latest version.

update portainer version

---

dcompose-stack/radar-cp-hadoop-stack/lib/util.sh
images/hsqldb/Dockerfile

Version 1 is deprecated and will stop working after 1 June, 2020
Certbot ref: https://certbot.eff.org/docs/using.html?highlight=hook#changing-the-acme-server

Use ACME protocol v2 for lets encrypt certificate

---

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml

Apparently, zookeeper logs were never correctly persisted. Note that this update will trigger a restart of the stack on the next install.
This issue was deduced via a separate issue noticed by @nivemaham that Kafka 2.4 would no longer start after a restart because Zookeeper did not persist its cluster ID.

Use correct zookeeper log directory

---

dcompose-stack/radar-cp-hadoop-stack/etc/webserver/nginx.conf.template
dcompose-stack/radar-cp-hadoop-stack/etc/webserver/nginx.nossl.conf.template

Small security fixes. Especially phasing out TLS 1.0 and 1.1 is important, they have been declared EOL long ago and are starting to generate warnings.
Edit: may also be applied to #218 if accepted.

Nginx security fixes

---

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml

Fixes zookeeper timeouts if the VM gets paused or the network temporarily gets congested. This is in line with the fix introduced in Kafka 2.5.0:
https://cwiki.apache.org/confluence/display/KAFKA/KIP-537%3A+Increase+default+zookeeper+session+timeout
Also move from deprecated schema registry zookeeper setting to new Kafka bootstrap server:
https://docs.confluent.io/4.1.1/schema-registry/docs/deployment.html#kafka-zookeeper

Relaxed zookeeper timeouts for spurious network or VM pauses

---

dcompose-stack/radar-cp-hadoop-stack/lib/systemd/radar-docker.service.template

Remove volumes after a restart of the radar-docker stack. This avoids the disk filling up when the stack is restarting continuously.

Remove stale volumes

---

dcompose-stack/radar-cp-hadoop-stack/README.md

This is to update the data extraction docs which is causing confusion for the majority of community deployments.

Update readme instructions causing confusion

---

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml

This should fix the gateway being unhealthy all the time, but needs to be tested still. Might be related to #243?

change gateway healthcheck to use curl instead of wget
