RADAR-base/RADAR-Docker

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
=> add dashboard container to docker-compose.yml

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml, dcompose-stack/radar-cp-swarm-stack/README.md, dcompose-stack/radar-cp-swarm-stack/docker-compose.yml
Deploy the docker-compose stack on a swarm cluster with overlay networking (with the exception of hadoop components) 
```sh
$ docker deploy --compose-file docker-compose.yml radar-cns-stack
```
- using EC2 Cloud Formation template (Docker 1.13.x) 
- https://beta.docker.com/docs/aws/release-notes/
- docker-compose doesn't work with docker-compose.yml v3
- https://hackernoon.com/deploy-docker-compose-v3-to-swarm-mode-cluster-4159e9cca712#.8p5wjldbo
=> create docker-compose.yml v3, rm hadoop from stack

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
Add some basic system monitors
=> Monitoring of the docker-compose stack

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml, images/radar-restapi/Dockerfile, images/radar-restapi/README.md
Updated REST-Api version to v0.1.1
=> Rest-api v0.1.1

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml, dcompose-stack/radar-cp-hadoop-stack/etc/nginx.conf.template
will now work with latest dockerhub dashboard build, which has also been fixed
=> fixing dashboard integration

dcompose-stack/radar-cp-hadoop-stack/etc/managementportal/changelogs/config/liquibase/oauth_client_details.csv.template, dcompose-stack/radar-cp-hadoop-stack/etc/nginx.conf.template, dcompose-stack/radar-cp-hadoop-stack/install-radar-stack.sh
- Add a line in install-radar-stack.sh to generate the keystore for JWT signing
- Update the OAuth clients details for use with the new authorization mechanisms
=> Fixes for updated ManagementPortal

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
To solve https://github.com/RADAR-CNS/ManagementPortal/issues/113
=> Update postgres volume to data

.travis.yml, dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml, dcompose-stack/radar-cp-hadoop-stack/etc/.gitignore, dcompose-stack/radar-cp-hadoop-stack/etc/webserver/cors.conf, dcompose-stack/radar-cp-hadoop-stack/etc/webserver/nginx.conf.template, dcompose-stack/radar-cp-hadoop-stack/install-radar-stack.sh
Add CORS headers to nginx. Fixes #73.
=> Enable cors for selected services

dcompose-stack/radar-cp-hadoop-stack/docker-kacc.sh
I wrote this months ago, I am sure there are improvements to be made, but so far it worked for me.
If you have suggestions please feel free to add.
=> script for using kafka-avro-console-consumer inside the platform

dcompose-stack/radar-cp-hadoop-stack/etc/.gitignore, dcompose-stack/radar-cp-hadoop-stack/install-radar-stack.sh, images/radar-hdfs-connector/Dockerfile, images/radar-hdfs-connector/kafka_status.sh, images/radar-mongodb-connector/Dockerfile, images/radar-mongodb-connector/kafka_status.sh
Reordered install script to fail fast and fixed connector images.
=> Install reordering

dcompose-stack/radar-cp-hadoop-stack/README.md, dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml, dcompose-stack/radar-cp-hadoop-stack/etc/radar.yml.template, images/radar-backend-kafka/Dockerfile, images/radar-backend-kafka/kafka_status.sh, images/radar-mongodb-connector/Dockerfile
Use the latest versions of docker images for some components. Depends on #86  
Docker hub link - https://hub.docker.com/u/radarcns/
Created new releases for [RADAR MongoDB Sink Connector 0.1](https://github.com/RADAR-CNS/RADAR-MongoDB-Sink-Connector/releases/tag/0.1) and [RADAR Backend 0.1](https://github.com/RADAR-CNS/RADAR-Backend/releases/tag/0.1).
=> Update versions according to Docker hub images

dcompose-stack/radar-cp-hadoop-stack/README.md, dcompose-stack/radar-cp-hadoop-stack/install-systemd-wrappers.sh, dcompose-stack/radar-cp-hadoop-stack/lib/systemd/radar-check-health.service.template, dcompose-stack/radar-cp-hadoop-stack/lib/systemd/radar-check-health.timer.template, dcompose-stack/radar-cp-hadoop-stack/lib/systemd/radar-renew-certificate.service.template, dcompose-stack/radar-cp-hadoop-stack/lib/systemd/radar-renew-certificate.timer.template
=> Add systemd services

dcompose-stack/radar-cp-hadoop-stack/check-health.sh
Add a 'healthy again' message to hipchat, and store the unhealthy service names in a temporary hidden file.
=> Add hipchat healthy message

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml, dcompose-stack/radar-cp-hadoop-stack/etc/mongodb-connector/sink-mongo.properties.template, dcompose-stack/radar-cp-hadoop-stack/etc/radar-backend/radar.yml.template, dcompose-stack/radar-cp-hadoop-stack/kafka-radarinit/Dockerfile, dcompose-stack/radar-cp-hadoop-stack/kafka-radarinit/topic_init.sh
- Use latest schema version
- Fix configs and properties
- Fix healthcheck
=> Latest schema

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml, dcompose-stack/radar-cp-hadoop-stack/kafka-radarinit/init.sh
Fix initialisation of topics by parsing Avro schemas that are not dependent on any others first.
=> Fix topic initialization

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml, dcompose-stack/radar-cp-hadoop-stack/etc/radar-backend/radar.yml.template
Fix Stream and broker properties
Related to https://github.com/RADAR-base/RADAR-Backend/issues/60
=> Fix Streams

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
Fix zookeeper health check references
=> Zookeeper health

dcompose-stack/radar-cp-hadoop-stack/hash-backup/README.md, dcompose-stack/radar-cp-hadoop-stack/hash-backup/backup.conf, dcompose-stack/radar-cp-hadoop-stack/hash-backup/dest.conf, dcompose-stack/radar-cp-hadoop-stack/hash-backup/initialize-hb.sh, dcompose-stack/radar-cp-hadoop-stack/hash-backup/run-backup.sh, dcompose-stack/radar-cp-hadoop-stack/hash-backup/systemd/radar-hashbackup.service.template, dcompose-stack/radar-cp-hadoop-stack/hash-backup/systemd/radar-hashbackup.timer.template
Add hash backup for more unified backups
Closes #106
=> Hash backup

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml, scripts/README.md, scripts/hdfs-data-retention/hdfs_data_retention.sh, scripts/hdfs-data-retention/hdfs_get_relevant_files.pig, scripts/hdfs-data-retention/topics_to_remove.txt
Delete files from hdfs based on date/time and topics using FS image file from namenode and processing it using apache pig.
=> Add script for deleting hdfs data based on date and topic

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml, dcompose-stack/radar-cp-hadoop-stack/etc/radar-backend/radar.yml.template, dcompose-stack/radar-cp-hadoop-stack/install-radar-stack.sh, dcompose-stack/radar-cp-hadoop-stack/util.sh
Also increase `_schemas` topic timeout and updated alpine versions
=> Increase offsets timeout (fixes #142)

dcompose-stack/radar-cp-hadoop-stack/images/radar-kafka-init/Dockerfile
See RADAR-Base/ManagementPortal#291
=> Revert to older schemas to fix ManagementPortal

dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
Updated to latest Management Portal
=> Updated to latest Management Portal

dcompose-stack/radar-cp-hadoop-stack/README.md, dcompose-stack/radar-cp-hadoop-stack/images/hdfs/Dockerfile, dcompose-stack/radar-cp-hadoop-stack/images/hdfs/hdfs-site.xml.mustache, dcompose-stack/radar-cp-hadoop-stack/lib/perform-install.sh
Allows for extending the capacity of hadoop
=> Enable multiple path for hdfs storage and instructions

dcompose-stack/radar-cp-hadoop-stack/Migrating-ManagementPortal-from-0.5.3-to-higher.md, dcompose-stack/radar-cp-hadoop-stack/README.md, dcompose-stack/radar-cp-hadoop-stack/bin/keystore-init, dcompose-stack/radar-cp-hadoop-stack/docker-compose.yml
- Upgrades MP and gateway versions
- Adds guide on manually migrating the environment
=> Upgrade to mp 0.5.4

dcompose-stack/radar-cp-hadoop-stack/etc/webserver/nginx.conf.template, dcompose-stack/radar-cp-hadoop-stack/etc/webserver/nginx.nossl.conf.template
=> Add cors support to schema registry

dcompose-stack/radar-cp-hadoop-stack/lib/perform-install.sh, dcompose-stack/radar-cp-s3-stack/lib/perform-install.sh
...coz "the tools for topic/schema registration are now under radarbase/radar-schemas-tools".
=> Replace radarbase/kafka-init with radarbase/radar-schemas-tools
